### ISSUE TITLE
In Use pin Grip Initiator no longer exist on node IsDenyingGrip

### ISSUE THREAD

**Issue by zmifsx** [mordentral/VRExpPluginExample#8]
Compiled from branch UE4.26_locked

Is breaking the link enough or there's need fixing somewhere else?
There's two other same errors and I tried breaking the link, compiles fine but asking just in case it's important. 
![awdaw](https://user-images.githubusercontent.com/58888818/135498787-706d40bd-c828-4087-9b99-ccaa5558aa80.PNG)

**Comment by mordentral** [comment]
You copied in the plugin seperately? The example comes with the correct plugin version for it already.

**Comment by mordentral** [comment]
That looks like you copied in an older precompiled binary version of the plugin , so yes you can unlink those nodes if you never need to check the hand when denying, but typically you should have just compiled the template as it came. Or used the plugins 4.26 branch instead of the precompiled binaries (those stay in their last version when the engine is updated but I keep porting fixes and new features to the actual repositories).

**Comment by zmifsx** [comment]
> 
> 
> That looks like you copied in an older precompiled binary version of the plugin , so yes you can unlink those nodes if you never need to check the hand when denying, but typically you should have just compiled the template as it came. Or used the plugins 4.26 branch instead of the precompiled binaries (those stay in their last version when the engine is updated but I keep porting fixes and new features to the actual repositories).

Everything is fine with the 4.26 branch plugins. Thanks!
